### ISSUE TITLE
请问如何使用print打印float或double

### ISSUE THREAD

**Issue by masterQian** [cppfastio/fast_io#12]
会爆异常,int是正常的

**Comment by AbrasiveBoar902** [comment]
请问你的代码是怎么写的，我实测并没有问题（

**Comment by masterQian** [comment]
#include <fast_io.h>
int main(){
    print(1.2);
}

就是一句，用的是MSVC编译器，Win32，只有float或double会爆异常。
异常所在文件是intrinsics.h，所在函数是inline constexpr bool add_carry(bool carry,T a,T b,T& out) noexcept;

异常位置位于50行：
else if constexpr(sizeof(T)==4)
return _addcarryx_u32(carry,a,b,reinterpret_cast<std::uint32_t*>(__builtin_addressof(out)));

异常信息：
0x0020B95D 处有未经处理的异常(在 test.exe 中): 0xC000001D: Illegal Instruction。

**Comment by trcrsired** [comment]
不知道什么情况，无法测试出来。

**Comment by farteryhr** [comment]
https://en.wikipedia.org/wiki/Intel_ADX cpu太老了没这个指令？

**Comment by trcrsired** [comment]
现在已经好了吧。
