### ISSUE TITLE
print() 在有阻塞的情况下无法打印

### ISSUE THREAD

**Issue by HWZen** [cppfastio/fast_io#19]
下面样式的代码
```
print("something");

socket.recv(); //或是别的会引发阻塞的代码

```
会导致print()无法打印，或打印不完全
如print("Hello")会打印成Hel
在阻塞结束后继续打印

在Qt环境下大概率无法打印

**Comment by HWZen** [comment]
难道print()是把内容存到缓冲区，然后专门有个线程去打印缓冲区的吗？

**Comment by trcrsired** [comment]
手工fflush(stdout)或者flush(fast_io::c_stdout())。

它在缓冲区里没写。
