### ISSUE TITLE
Todo: Remove freestanding workarounds to use C++23 standard headers for freestanding

### ISSUE THREAD

**Issue by trcrsired** [cppfastio/fast_io#267]
Since C++23, more headers and features (like std::addressof) are available now. Therefore, we need to remove all the workaround.

GCC provides extensions like making `<array>` and `<span>` be also in the freestanding C++ toolchain. However, we will still avoid them unless the C++ standard says something.

This will trim the library and make it more "standardized."

**Comment by havedifficultyinfindingnames** [comment]
#273 changes around freestanding part will be made on branch 'experimental', and will not be merged before it's clear that no bugs are triggered by these changes.

**Comment by havedifficultyinfindingnames** [comment]
all benchmarks, tests and examples have passed. 'experimental' branch merged

**Comment by trcrsired** [comment]
Done
