### ISSUE TITLE
fuzzer crash in addrprt

### ISSUE THREAD

**Issue by havedifficultyinfindingnames** [cppfastio/fast_io#496]
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3104459081
INFO: Loaded 1 modules   (431 inline 8-bit counters): 431 [0x55728be4c640, 0x55728be4c7ef),
INFO: Loaded 1 PC tables (431 PCs): 431 [0x55728be4c7f0,0x55728be4e2e0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED cov: 2 ft: 2 corp: 1/1b exec/s: 0 rss: 36Mb
        NEW_FUNC[1/11]: error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x2133c
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x24399
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x24e91
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x3102b
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x3ecfd
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x42956
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x43313
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x44e26
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x46295
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x46ca9
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x48110
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x481f8
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x4820f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x48280
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x4dd6f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x4e354
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x4e69d
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x4fda9
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x51158
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x546ba
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x54fda
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x56183
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x85eba
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x89de9
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x89fe9
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8afb9
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8b466
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8cc14
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8ce63
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8f5dc
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8f97f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8fe0f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x8fef3
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9045a
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9063a
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x91bb6
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x91e10
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9499e
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x94e3b
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x96ffe
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x975bf
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x982bc
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9852d
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9883d
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x98dc9
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x998c7
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x99c7a
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x99ca5
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9a322
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9aaab
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9afda
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9b173
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9b71d
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9b929
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9db4c
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9dd52
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9e025
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9e0a5
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9e992
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9edc8
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9fc3c
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0x9fd6e
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa00a6
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa0330
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa074f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa24aa
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa2e00
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa2fa1
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa39d4
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa3ae1
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa3e5c
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa3f0c
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa4fa4
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa5884
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa627f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa64f8
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa8dae
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa90c9
error: did not detect a valid list table with base = 0x0
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa99ea
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa9b4b
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xa9cd2
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xaaf8f
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xab385
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xab4da
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xab97b
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xabd4c
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xabda2
error: did not detect a valid list table with base = 0x0
error: decoding address ranges: invalid range list offset 0xabec0
0x55728bdfe090 in char* fast_io::details::prtrsv_inaddr_common_define_impl<char>(char*, unsigned char const*) ../../include/fast_io_core_impl/socket/addrprt.h:11
        NEW_FUNC[2/11]: 0x55728bdfe730 in char* fast_io::details::jeaiii::jeaiii_tree<0ul, 9ul, char>(char*, unsigned int) ../../include/fast_io_core_impl/integers/jeaiii_method.h:134
#1031   NEW    cov: 99 ft: 100 corp: 2/15b lim: 14 exec/s: 515 rss: 37Mb L: 14/14 MS: 4 InsertRepeatedBytes-EraseBytes-InsertRepeatedBytes-CrossOver-
#1035   NEW    cov: 101 ft: 112 corp: 3/29b lim: 14 exec/s: 517 rss: 37Mb L: 14/14 MS: 4 ChangeBit-ChangeBit-ChangeByte-ChangeBinInt-
#1056   NEW    cov: 101 ft: 126 corp: 4/43b lim: 14 exec/s: 528 rss: 37Mb L: 14/14 MS: 1 ChangeByte-
#1065   NEW    cov: 101 ft: 141 corp: 5/57b lim: 14 exec/s: 532 rss: 37Mb L: 14/14 MS: 4 ChangeByte-CopyPart-ChangeBinInt-CrossOver-
#1079   NEW    cov: 101 ft: 144 corp: 6/71b lim: 14 exec/s: 539 rss: 37Mb L: 14/14 MS: 4 ChangeByte-CrossOver-ChangeByte-CopyPart-
#1090   NEW    cov: 103 ft: 147 corp: 7/85b lim: 14 exec/s: 545 rss: 37Mb L: 14/14 MS: 1 ChangeBinInt-
#1108   NEW    cov: 103 ft: 157 corp: 8/99b lim: 14 exec/s: 554 rss: 37Mb L: 14/14 MS: 3 ShuffleBytes-ShuffleBytes-ChangeBinInt-
#1154   NEW    cov: 104 ft: 159 corp: 9/113b lim: 14 exec/s: 577 rss: 37Mb L: 14/14 MS: 1 ShuffleBytes-
#1183   NEW    cov: 108 ft: 181 corp: 10/127b lim: 14 exec/s: 591 rss: 37Mb L: 14/14 MS: 4 ShuffleBytes-EraseBytes-CMP-CrossOver- DE: "\001\000\000\000\000\000\000\000"-
#1193   NEW    cov: 108 ft: 183 corp: 11/141b lim: 14 exec/s: 596 rss: 37Mb L: 14/14 MS: 5 CopyPart-ShuffleBytes-ChangeByte-ShuffleBytes-CopyPart-
#1205   NEW    cov: 109 ft: 184 corp: 12/155b lim: 14 exec/s: 602 rss: 37Mb L: 14/14 MS: 2 CrossOver-ChangeByte-
#1222   NEW    cov: 109 ft: 188 corp: 13/169b lim: 14 exec/s: 611 rss: 37Mb L: 14/14 MS: 2 ChangeByte-CrossOver-
==209== ERROR: libFuzzer: deadly signal
error: did not detect a valid list table with base = 0x0
warning: parsing line table prologue at 0x0000af25 should have ended at 0x0000b267 but it ended at 0x0000b266
    #0 0x55728bdc15fa in __sanitizer_print_stack_trace (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x1695fa)
    #1 0x55728bccaae4 in fuzzer::PrintStackTrace() (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x72ae4)
    #2 0x55728bcadc56 in fuzzer::Fuzzer::CrashCallback() (.part.0) (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x55c56)
    #3 0x55728bcadd16 in fuzzer::Fuzzer::StaticCrashSignalCallback() (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x55d16)
    #4 0x7fa349b0c41f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #5 0x7fa3498f600a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #6 0x7fa3498f600a in raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #7 0x7fa3498d5858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
    #8 0x7fa349d23809  (/usr/local/lib64/libstdc++.so.6+0xb9809)
    #9 0x7fa349d23874 in std::terminate() (/usr/local/lib64/libstdc++.so.6+0xb9874)
    #10 0x55728bdfe08a in __clang_call_terminate (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x1a608a)
    #11 0x55728bdfe079 in LLVMFuzzerTestOneInput /mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/validate_scan.cc:29:15
    #12 0x55728bcae16c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x5616c)
    #13 0x55728bcb05a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x585a0)
    #14 0x55728bcb16e0 in fuzzer::Fuzzer::MutateAndTestOne() (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x596e0)
    #15 0x55728bcb2717 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x5a717)
    #16 0x55728bc93876 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x3b876)
    #17 0x55728bc7f602 in main (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x27602)
    #18 0x7fa3498d7082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #19 0x55728bc7f64d in _start (/mnt/d/vsfiles/fast_io_forked/fuzzing/0009.ipv6/a.out+0x2764d)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 3 CMP-CopyPart-CMP- DE: "Q\316BG\243\177\000\000"-"\001\000\000\000\000\000\000\000"-; base unit: 4fccbe254cb215e8e1a08cff5cb082587a63676b
0x0,0xcc,0xa,0x0,0x4c,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x47,
\000\314\012\000L\001\000\000\000\000\000\000\000G
artifact_prefix='./'; Test unit written to ./crash-c78245096f3c6d73a4d5b4a878f335c2b630a733
Base64: AMwKAEwBAAAAAAAAAEc=

**Comment by havedifficultyinfindingnames** [comment]
#495

**Comment by havedifficultyinfindingnames** [comment]
@trcrsired

**Comment by trcrsired** [comment]
Not a bug. to function throws exceptions.
