### ISSUE TITLE
Suggest launching a fast_log based on fast_io

### ISSUE THREAD

**Issue by UMU618** [cppfastio/fast_io#499]
建议 cppfastio 推出一个基于 fast_io 的 fast_log。
目前的 Boost.Log 和 glog 看起来都不如即将推出的 fast_log。
宣传到位！

**Comment by debuggingbug** [comment]
https://github.com/MengRao/fmtlog
这个是基于 fmt 的 log，我测试过 fmt 不如 fast_io。

**Comment by YexuanXiao** [comment]
fast_io直接输出到文件就很快。

**Comment by debuggingbug** [comment]
> fast_io直接输出到文件就很快。

再快也是同步，不做前端和后端分离、支持异步，就不能算是 log 库。
