### ISSUE TITLE
fast_io failing with GCC 13.0.1; no issues with GCC 12.2.0.

### ISSUE THREAD

**Issue by marioroy** [cppfastio/fast_io#531]
Blessings and grace. Thank you, for this wonderful library.

I'm testing Fedora 38 which provides GCC 13.0.1. 

```text
#include <fast_io.h>
```

```text
$ g++ --version
g++ (GCC) 13.0.1 20230401 (Red Hat 13.0.1-0)

$ g++ -o llil4vec -std=c++20 -Wall -O3 llil4vec.cpp -I ./fast_io/include
In file included from ./fast_io/include/fast_io_core.h:49,
                 from ./fast_io/include/fast_io_freestanding.h:12,
                 from ./fast_io/include/fast_io_hosted.h:17,
                 from ./fast_io/include/fast_io.h:9,
                 from llil4vec.cpp:51:
./fast_io/include/fast_io_core_impl/utils.h: In instantiation of ‘constexpr const long unsigned int fast_io::details::compile_pow10<long unsigned int, 18>’:
./fast_io/include/fast_io_core_impl/integers/uprsv/dec.h:274:43:   required from here
./fast_io/include/fast_io_core_impl/utils.h:478:50: error: ‘constexpr T fast_io::details::compile_time_pow(T, std::size_t) [with T = long unsigned int; std::size_t = long unsigned int]’ used before its definition
  478 | inline constexpr T compile_pow10{compile_time_pow(std::remove_cvref_t<T>(10),pow)};
      |                                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by trcrsired** [comment]
i am investigating it

**Comment by trcrsired** [comment]
do not know what is going on. I use GCC 13.0.1 too but I do not see the issue

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/13.0.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../../../../gcc/configure --disable-nls --disable-werror --enable-multilib --disable-bootstrap --disable-libstdcxx-verbose --with-gxx-libcxx-include-dir=/usr/local/include/c++/v1 --with-pkgversion=cqwrteur --with-multilib-list=m64,m32,mx32 --with-libstdcxx-eh-pool-obj-count=0 --enable-languages=c,c++ --enable-libstdcxx-backtrace
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.0.1 20230205 (experimental) (cqwrteur)

Probably I need to build a new one.

**Comment by trcrsired** [comment]
Can you show me your example so I may repeat it?

**Comment by marioroy** [comment]
The llil4vec.cpp example is from PerlMonks.
https://perlmonks.org/?node_id=11149545

More info here (for generating the input files).
https://perlmonks.org/?node_id=11149907

**Comment by trcrsired** [comment]
https://perlmonks.org/?node_id=11149907

Are you trying for benchmarking?

I have a suggestion for you here. Do not use standard library pair or tuple. Just rewrite struct.


I do not find where the source. Can you give me a screenshot or just give me the link?

BTW. GCC is 14 now.

**Comment by marioroy** [comment]
On the https://perlmonks.org/?node_id=11149545 page, there should be a see more or download (at the end of the llil4vec.cpp code).

Well, I made a gist containing llil4vec.cpp.
https://gist.github.com/marioroy/a3cd861973b4949fc7af322b04dbe9e7

**Comment by trcrsired** [comment]
I've seen that.

Have a question:

Why do you use:

::print(fast_io::concatln(fast_io::mnp::os_c_str(n.first.data(),
+ MAX_STR_LEN_L), "\t", n.second));

instead of just

println(fast_io::mnp::os_c_str(n.first.data(),+ MAX_STR_LEN_L), "\t", n.second));
?

**Comment by trcrsired** [comment]
> Thank you, for your suggestion.
> 
> On the https://perlmonks.org/?node_id=11149545 page, there should be a see more or download (at the end of the llil4vec.cpp code).
> 
> https://perlmonks.org/?node_id=11149545;displaytype=displaycode;abspart=1;part=3
> 
> Well, I made a gist containing llil4vec.cpp just in case. https://gist.github.com/marioroy/a3cd861973b4949fc7af322b04dbe9e7

I have seen that, and I can use fast_io to easily improve the performance of the entire program. This program is written poorly.

**Comment by marioroy** [comment]
> This program is written poorly.

I'm very new to C++. The program is based on code from another monk. I introduced to the monk fast_io.

**Comment by marioroy** [comment]
Thank you, for your suggestion. We struggled learning fast_io, particularly on where how to make fast faster. I'm new to C++, so tried to go through the code, the doc may not make some things obvious or I missed it somewhere.

**Comment by trcrsired** [comment]
I am rewriting your code in fast_io to show it as an example.

Many features you are using are provided by fast_io, including memory-mapped files. Line scanner, integer scanning, etc. They are optimized with SIMD on fast_io.

**Comment by trcrsired** [comment]
if (argc < 2) {
      std::cerr << "usage: llil4vec file1 file2 ... >out.txt\n";
      return 1;
   }
   this is usually a bad idea since argc is 0. the first parameter better be *argv

**Comment by marioroy** [comment]
> if (argc < 2) {

We were carried away with the performance improvements over many iterations. I will fix my examples.

> I am rewriting your code in fast_io to show it as an example.

Thank you! We struggled learning the fast_io library; often having to look at the code to understand.

**Comment by trcrsired** [comment]
where is shuffle.pl??

**Comment by marioroy** [comment]
> where is shuffle.pl??

Ah, that is the tiny Perl code (6 lines) at the top of this page.

https://perlmonks.org/?node_id=11149800

**Comment by trcrsired** [comment]
Can you join fast_io's discord?

**Comment by trcrsired** [comment]
https://github.com/trcrsired/llil4vec-fast_io/blob/main/llil4vec-fast_io.cc

**Comment by marioroy** [comment]
>      if(val<0)
>      {
>         ::std::size_t count = static_cast<::std::size_t>(static_cast<::std::size_t>(0)-count);
>      }

That will not work. Reason, std::size_t is an unsigned type.

Next, the else is not needed. The first timed result is "get properties". 

```text
$ diff llil4vec-fast_io.cc.orig llil4vec-fast_io.cc
216,217d215
< #else
<    int nthrs = 1;
262c260
<    perr("sort properties     ",ctaken1," secs\n");
---
>    perr("get properties      ",ctaken1," secs\n");
```

Test first using 1 core, no OpenMP. In the original code, I also enabled memory mapped IO; e.g. changing `#if 0` to `#if 1`.

The get_properties run much faster than before. There's an anomaly, as the overall time is slower; e.g. other parts of the program run slower possibly due to less use of L2/L3 cache. It also impacts writing to standard output.

Get properties:
```text
Before: 0.530 seconds
Before: 0.368 seconds (using MemoryMapped.h)
 After: 0.236 seconds (llil4vec-fast_io)
```

Write stdout:
```text
Before: 0.201 seconds
Before: 0.201 seconds (using MemoryMapped.h)
 After: 0.362 seconds (llil4vec-fast_io)
```

 Total time:
```text
Before: 1.279 seconds
Before: 1.124 seconds (using MemoryMapped.h)
 After: 1.491 seconds (llil4vec-fast_io)
```

Btw: fast_io will not compile on Fedora 38 (GCC 13.0.1). The error above is clear as to why. Something inside fast_io is being used before its definition. Fedora Linux possibly applied patches to GCC 13 performing additional checks.

So, I installed Debian GCC 12.2.0 to /opt/gcc-12.

GCC 12.2 on Fedora 38.
https://gist.github.com/marioroy/6d4c055d970bdff0492db75f76dae842

**Comment by marioroy** [comment]
The benefit of llil4vec-fast_io.cc is lesser memory consumption. The side effect is less benefit of L3 cache. I ran again with 23 big files (using 1 core) and monitored memory consumption in another terminal window.

```text
Before:  4.6 GB
 After:  2.5 GB 
```

**Comment by trcrsired** [comment]
https://github.com/trcrsired/llil4vec-fast_io/blob/main/llil4vec-fast_io_nostd.cc

What about this now? It does not use any actual memory I think.

**Comment by marioroy** [comment]
Wow! That is amazing.

Input 3 big files:

Get properties:
```text
Before: 0.530 seconds
Before: 0.368 seconds (using MemoryMapped.h)
 After: 0.236 seconds (llil4vec-fast_io)
 After: 0.156 seconds (llil4vec-fast_io_nostd)
```

Write stdout:
```text
Before: 0.201 seconds
Before: 0.201 seconds (using MemoryMapped.h)
 After: 0.362 seconds (llil4vec-fast_io)
 After: 0.343 seconds (llil4vec-fast_io_nostd)
```

 Total time:
```text
Before: 1.279 seconds
Before: 1.124 seconds (using MemoryMapped.h)
 After: 1.491 seconds (llil4vec-fast_io)
 After: 0.703 seconds (llil4vec-fast_io_nostd)
```

Input 23 big files:

```text
Before:  4.6 GB
 After:  2.5 GB (llil4vec-fast_io)
 After:  3.1 GB (llil4vec-fast_io_nostd)
```

**Comment by trcrsired** [comment]
join discord:
https://discord.gg/zhZhcG24qu

so we can help you
