### ISSUE TITLE
print '\t' doesn't perform as expected

### ISSUE THREAD

**Issue by backyardofysh** [cppfastio/fast_io#558]
Or is my understanding wrong?
main.cpp
```cpp
#include <fast_io.h>
using namespace fast_io::io;

int main()
{
	println(0, '\t', 90, '\t', 0);
	println(0, "\t", 90, "\t", 0);
}
```

both msvc and gcc will give the output
099090
0       90       0

**Comment by havedifficultyinfindingnames** [comment]
I'm wrong. Using ```mnp::chvw``` to output a single char

**Comment by YexuanXiao** [comment]
C++应该加个static_warning（

**Comment by trcrsired** [comment]
This is a feature. not a bug
