### ISSUE TITLE
[FYI] compilation error on gcc13 with tautological-compare

### ISSUE THREAD

**Issue by toge** [cppfastio/fast_io#561]
It is almost same issue as https://github.com/cppfastio/fast_io/issues/531.
This is not a bug issue about fast_io, but it may be beneficial to those who use fast_io with gcc13.
If there is no problem, you can close it immediately.

I met a following compilation errors on 20230810 snapshot with gcc 13:
```
‘constexpr T fast_io::details::compile_time_pow(T, std::size_t) [with T = long unsigned int; std::size_t = long unsigned int]’ used before its definition
  478 | inline constexpr T compile_pow10{::fast_io::details::compile_time_pow<::std::remove_cvref_t<T>>(10,pow)};
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
```

It seems to be caused by "-Wtautological-compare".
fast_io test code work fine for me with gcc "-Wall -Wextra -Wno-tautological-compare".

**Comment by Sendan4** [comment]
-Wall cause this error for my

using fedora 38 with g++ 13.2.1 and CMake 3.27.4

**Comment by trcrsired** [comment]
is it fixed?

**Comment by Sendan4** [comment]
> is it fixed?

Yes, it's working with GCC on Windows and Linux, thank you 😺

**Comment by trcrsired** [comment]
looks like a GCC bug

**Comment by trcrsired** [comment]
i will file a bug report to GCC to recreate the issue

**Comment by trcrsired** [comment]
fixed
