### ISSUE TITLE
example1的helloworld_android_remote_dbg编译不通过

### ISSUE THREAD

**Issue by cup825** [cppfastio/fast_io#684]
fast_io\examples\0001.helloworld\helloworld_android_remote_dbg.cc

error C1083: 无法打开包括文件: “android/log.h”: No such file or directory

**Comment by trcrsired** [comment]
你是给安卓编译的么？

**Comment by cup825** [comment]
在 VS 里直接跑的

> 你是给安卓编译的么？

**Comment by trcrsired** [comment]
那肯定过不了。这个只有安卓目标才能用的。你可以直接用通用的dbg()。这样可以输出到vs的调试器
