### ISSUE TITLE
can't build an example from documentation

### ISSUE THREAD

**Issue by cnt0** [cppfastio/fast_io#742]
From https://gitee.com/qabeowjbtkwb/fast_io/wikis/0018.-custom-type (https://ewindy.gitee.io/fast_io_rst/index.html shows status 504, gateway timeout)

```cpp
#include <fast_io.h>

struct a_custom_type {
  int x = 5;
};

constexpr void print_define(auto stm, a_custom_type const &t) {
  fast_io::io::print(stm, t.x);
}

int main(int argc, char *argv[]) {
  fast_io::io::print(a_custom_type{});
}
```

```bash
$ g++ -std=c++23 -Ifast_io/include main.cpp -o main
In file included from main.cpp:1:
fast_io/include/fast_io.h: In instantiation of 'constexpr void fast_io::io::print(T&&, Args&& ...) [with T = a_custom_type; Args = {}]':
main.cpp:14:21:   required from here
fast_io/include/fast_io.h:271:15: error: static assertion failed: some types are not printable for print on default C's stdout
  271 | static_assert(type_error,"some types are not printable for print on default C's stdout");
      |               ^~~~~~~~~~
fast_io/include/fast_io.h:271:15: note: 'type_error' evaluates to false
```
after skimming through fast_io concepts, I was able to work around that:
```cpp
constexpr void print_define(auto _dummy, auto stm, a_custom_type const &t) {
  fast_io::io::print(stm, t.x);
}
```
I don't know whether this is a bug in fast_io or just outdated docs

**Comment by trcrsired** [comment]
> From https://gitee.com/qabeowjbtkwb/fast_io/wikis/0018.-custom-type (https://ewindy.gitee.io/fast_io_rst/index.html shows status 504, gateway timeout)
> 
> ```c++
> #include <fast_io.h>
> 
> struct a_custom_type {
>   int x = 5;
> };
> 
> constexpr void print_define(auto stm, a_custom_type const &t) {
>   fast_io::io::print(stm, t.x);
> }
> 
> int main(int argc, char *argv[]) {
>   fast_io::io::print(a_custom_type{});
> }
> ```
> 
> ```shell
> $ g++ -std=c++23 -Ifast_io/include main.cpp -o main
> In file included from main.cpp:1:
> fast_io/include/fast_io.h: In instantiation of 'constexpr void fast_io::io::print(T&&, Args&& ...) [with T = a_custom_type; Args = {}]':
> main.cpp:14:21:   required from here
> fast_io/include/fast_io.h:271:15: error: static assertion failed: some types are not printable for print on default C's stdout
>   271 | static_assert(type_error,"some types are not printable for print on default C's stdout");
>       |               ^~~~~~~~~~
> fast_io/include/fast_io.h:271:15: note: 'type_error' evaluates to false
> ```
> 
> after skimming through fast_io concepts, I was able to work around that:
> 
> ```c++
> constexpr void print_define(auto _dummy, auto stm, a_custom_type const &t) {
>   fast_io::io::print(stm, t.x);
> }
> ```
> 
> I don't know whether this is a bug in fast_io or just outdated docs

outdated docs.

```cpp
template<std::integral char_type>
constexpr void print_define(::fast_io::io_reserve_type_t<char_type,a_custom_type>, auto stm, a_custom_type const& t)
{
    fast_io::io::print(stm, t.x);
}
```
