### ISSUE TITLE
scan(..., <string with space>) seems to stop at first space character

### ISSUE THREAD

**Issue by ta-o666** [cppfastio/fast_io#764]
Running the below code with "hello world" as the input outputs "hello" when it should output "hello world".
```c++
#include <string>
#include <fast_io.h>

using namespace fast_io::io;

int main()
{
    std::string str;
  
    scan(str);
    print(str);
}
```
Unless this is intentional and there is another scan function that scans the entire like like std::getline(...).

This bug(?) also makes it so that the example at https://gitee.com/qabeowjbtkwb/fast_io/wikis/0004.-file-IO for printing out a string from a file stops at the first space.

**Comment by ta-o666** [comment]
* compiled on vscode using g++.exe (mingw-x64)

**Comment by trcrsired** [comment]
not a bug. standard std::cin has the same behavior

What you need is line_get manipulator;

```cpp
std::string str;
using namespace ::fast_io::mnp;
scan(line_get(str));
```
or
```cpp
std::string str;
scan(::fast_io::mnp::line_get(str));
```
