### ISSUE TITLE
Add support for `clock_gettime` family on Apple (MacOSX)

### ISSUE THREAD

**Issue by akukh** [cppfastio/fast_io#781]
It would be great to see support for the `clock_gettime` family for MacOSX, at least for the latest versions where this feature is implemented by Apple. I recently tested this on a Sonoma 14.5 with
```c++
extern int libc_clock_gettime(clockid_t clk_id, struct timespec* tp) noexcept __asm__("_clock_gettime");
```
It worked.

**Comment by trcrsired** [comment]
> It would be great to see support for the `clock_gettime` family for MacOSX, at least for the latest versions where this feature is implemented by Apple. I recently tested this on a Sonoma 14.5 with
> 
> ```c++
> extern int libc_clock_gettime(clockid_t clk_id, struct timespec* tp) noexcept __asm__("_clock_gettime");
> ```
> 
> It worked.

Is there any version testing macro for Mac?

**Comment by trcrsired** [comment]
Fixed
