### ISSUE TITLE
Scan Integer with leading zero?

### ISSUE THREAD

**Issue by MaxMxMz** [cppfastio/fast_io#815]
Hello! 
integer data  - 01 02 0003   and so on ..... with leading zero

I Use example 
int main()
{
	char8_t a,b,c,d;
	scan(a,".",b,".",c,".",d);
	println(a,".",b,".",c,".",d);
}
if i enter 01.2.3.4 - i have exeption

I've tried 
scan("0", a);    - work, 
 but when data no have leading zero, i have exeption

**Comment by trcrsired** [comment]
Hi. This needs to use manipulator ```::fast_io::manipulator::base_get<10, false, true>(a)```

i have just found it only has ```bin_get``` and ```hex_get``` so i am adding ```dec_get``` and ```oct_get```.

```
template <::std::size_t bs, bool noskipws = false, bool skipzero = false, bool prefix = false, ::fast_io::details::my_integral scalar_type>
inline constexpr scalar_manip_t<::fast_io::details::base_scan_mani_flags_cache<bs, noskipws, (bs == 10 ? false : prefix), skipzero>,
								scalar_type &>
base_get(scalar_type &t) noexcept
{
	return {t};
}

template <bool noskipws = false, bool skipzero = false, ::fast_io::details::my_integral scalar_type>
inline constexpr scalar_manip_t<::fast_io::details::base_scan_mani_flags_cache<10, noskipws, false, skipzero>,
								scalar_type &>
dec_get(scalar_type &t) noexcept
{
	return {t};
}
```

The reason zeros are not skipped by default is that numbers starting with a 0 might be interpreted as octal (base 8) numbers, causing issues for things like IP addresses. This is an unfortunate consequence from UNIX.


Scanning with a string literal isn't meant for any kind of string pattern matching. It only means that next part of string in the stream must be that string. fast_io does not use any kind of format string at all.

**Comment by trcrsired** [comment]
BTW, in your example i think you need to set noskipws to be true too so it cannot skip spaces
