### ISSUE TITLE
Walled Garden APIs

### ISSUE THREAD

**Issue by trcrsired** [cppfastio/fast_io#826]
Unfortunately, due to monopoly, the computer industry gradually becomes walled gardens.

The library should provide a way to deal with walled garden apis

**Comment by MacroModel** [comment]
At present, there is no need to support it. It is meaningless. All walled garden systems can independently build a set of imperfect fs supported apis, and many functions may not be realized.

**Comment by trcrsired** [comment]
fk u

**Comment by trcrsired** [comment]
你啥都不懂不要在这装x可以不

https://learn.microsoft.com/en-us/windows/uwp/files/file-access-permissions

**Comment by YexuanXiao** [comment]
Fuck you, you adult baby, stop making harassing comments in other repo. I'm embarrassed to say I acquainted with you.

**Comment by trcrsired** [comment]
> Fuck you, you adult baby, stop making harassing comments in other repo. I'm embarrassed to say I acquainted with you.

你这狗东西支持围墙全家死光

**Comment by YexuanXiao** [comment]
尼特快给我解除屏蔽[恶心]

**Comment by YexuanXiao** [comment]
你已经屈服于围墙花园了[恶心]
