### ISSUE TITLE
What's the meaning of `u` in fast_io::mnp::uhexfull?

### ISSUE THREAD

**Issue by UMU618** [cppfastio/fast_io#845]
I guessed it is `unsigned`, but it's wrong, because the following codes print `-7fffffff`:

```ccp
int32_t n = 0x8000'0001;
fast_io::io::println(fast_io::mnp::uhexfull(n));
```

**Comment by trcrsired** [comment]
i forgot. sorry. But i think you can use ::fast_io::io::addrvw instead

**Comment by YexuanXiao** [comment]
小写，你可以用`uint32_t(n)`把n转换成无符号数来输出80000001。

**Comment by trcrsired** [comment]
> 小写，你可以用 `uint32_t(n)` 把 `n` 转换成无符号数来输出80000001。

应该输出什么？

**Comment by trcrsired** [comment]
fixed

**Comment by UMU618** [comment]
It's OK now!
