### ISSUE TITLE
Todo: Support teju

### ISSUE THREAD

**Issue by MacroModel** [cppfastio/fast_io#922]
dragonbox -> teju

**Comment by MacroModel** [comment]
https://github.com/cassioneri/teju_jagua/tree/main/teju

**Comment by trcrsired** [comment]
Are you sure it runs faster?

**Comment by MacroModel** [comment]
ask jk-jeon. he'd have accurate results if he'd tested it.

**Comment by MacroModel** [comment]
等出现完整且准确的基准时再考虑这个Issue
